### ISSUE TITLE
Default file should be in .config/myanimelist

### ISSUE THREAD

**Issue by masasin** [ryukinix/mal#1]
For the past few years, it's been best practice on Linux to have programs save their configuration in the .config directory. A subdirectory can be created when there are more than one file pertaining to the same program.

edit:

`DEFAULT_FILE = '~/.myanimelist.init'` should become `DEFAULT_FILE=~/.config/myanimelist`, and the readme would have to be updated.

**Comment by ryukinix** [comment]
Thanks for that suggestion! Is really a better this for Linux! By the way, exists someway to get the config folder for the user using a cross-plataform way? I will do this in soon!

**Comment by masasin** [comment]
I've only really used Linux for the past 8 years, so I have no idea what everybody else does. Sorry!

**Comment by masasin** [comment]
You can check the platform using  `sys.platform`. Linux is `linux` or `linux2`, OSX is `darwin`, and Windows is `win32` or `cygwin`

**Comment by ryukinix** [comment]
Yes, I can do that! But I was wants a way to avoid this, as I don't use OSX I even more Windows, so is a little painful to mantain this. I was checking on [sysconfig](https://hg.python.org/cpython/file/3.5/Lib/sysconfig.py) lib (stdlib), but she don't check the users path. But I found this lib called [appdirs](https://pypi.python.org/pypi/appdirs)! Appears be nice, no?

from the main page:

```
the problem

What directory should your app use for storing user data? If running on Mac OS X, you should use:

~/Library/Application Support/<AppName>
If on Windows (at least English Win XP) that should be:

C:\Documents and Settings\<User>\Application Data\Local Settings\<AppAuthor>\<AppName>
or possibly:

C:\Documents and Settings\<User>\Application Data\<AppAuthor>\<AppName>
for roaming profiles but that is another story.

On Linux (and other Unices) the dir, according to the XDG spec, is:

~/.local/share/<AppName>
```

Oy maybe this [usersettings](https://github.com/glvnst/usersettings) lib. I don't know yet which is better. I'll try test in soon and modify this.

**Comment by masasin** [comment]
I like appdirs. Thank you for this.
