### ISSUE TITLE
Weird messages output on urxvt

### ISSUE THREAD

**Issue by alexkubica** [ryukinix/mal#11]
I noticed that on urxvt terminal the output is messed up, see following [screencast](https://drive.google.com/open?id=0B9ehAG_Nj4CzWTRhb3ZoNENnem8).
Maybe it's a bug on urxvt?

**Comment by ryukinix** [comment]
HAHAHA, this is really funny. I have the same behavior on NT shell (windows). I don't understand yet this behavior, but using xfce4-terminal I don't have that problem  or even the termux on android!

**Comment by ryukinix** [comment]
You can give more information about your machine and your terminal emulator? (version e etc)

**Comment by ryukinix** [comment]
BTW, this a problem with https://github.com/ryukinix/decorating. You can create that same issue on that repository? I'll close that one, thanks.

**Comment by alexkubica** [comment]
Opened here: https://github.com/ryukinix/decorating/issues/17
