### ISSUE TITLE
Add subcommand config

### ISSUE THREAD

**Issue by ryukinix** [ryukinix/mal#2]
# Goal
## config

``` bash
> mal config
:: streaming:
1. superanimes (free server) (no credentials need) (pt-br)
2. crunchbag (paid server) (need credentials) (multilanguage)
select streaming source: 1
:: player
1. vlc
2. mplayer
select your player: 1
:: download:
1. anbient (pt-br)
2. another (?)
select download source: 1
```
# Specification
- [ ] create the list of supported streaming & download sources
- [ ] persists the configuration for:
  - [ ] streaming source
  - [ ] download source
  - [ ] default player

**Comment by alexkubica** [comment]
Should the lists of options be automatically generated?
Or should they be fixed?

**Comment by ryukinix** [comment]
Well, good question. We need give some options for the user based on a fixed list of servers and players, tested with mal and our implementation, but I think the user need choice how will works on your machine... Server & player.

**Comment by ryukinix** [comment]
Actually, is possible automatically generated a list of servers? We have that type of resource on some place of internet? This will be great.

**Comment by mparadinha** [comment]
I think we could have the default behaviour of `list` be an option for the user to choose with this command. And also maybe something like a colorscheme, though that might be a bit harder to implement. What do you think?

**Comment by ryukinix** [comment]
The command `config` actually is implemented just to list the configuration file and show its path. The `download` and `watch` relations of `config` will potentially be dropped in soon (see #4)

**Comment by ryukinix** [comment]
This config subcommand is not more related to download and watch. New params for the config subcommand should be added as a separated issue.
