### ISSUE TITLE
Curses interface for mal

### ISSUE THREAD

**Issue by alexkubica** [ryukinix/mal#29]
I've been wanting to make a curses interface for mal for a while now, I don't have much time free but someday maybe I'll get to it.  
It could be an extension for this project or it can be on a separate project. What do you think?

**Comment by ryukinix** [comment]
As you are an current contributor of the project, I guess this initially can be done in this repository on a separated branch. That way maybe I can help you on that more directly.

But if you prefer create a fork and do that separately, go on. 

There is some feature special you would wish had in mal to integrate curses for that? What you expect after done this?

**Comment by alexkubica** [comment]
I thout that if you add a flag like `--curses` it would display a curses interface.
I guess I'll start as a fork instead of doing it from scratch as I could use your python api 😃

**Comment by ryukinix** [comment]
Great.

**Comment by ryukinix** [comment]
I'm closing this issue because the lack of activity. Since someone have interest on that, I can open again. Thanks for all the support @AlexK-IL
