### ISSUE TITLE
Add subcommand download

### ISSUE THREAD

**Issue by ryukinix** [ryukinix/mal#3]
## download

``` bash
mal lain download next
==> downloading the epi ~x~
```
## Needs

~The #2 need to be fixed before.~
### Specification

~After calling download command, this will fetch the actual episode of the lain, get the next, search on the default download server configured and save him in the actual directory.~
- [ ] ~use urlretrieve and tqdm for download~
- [ ] ~allow pass a custom directory for saving~
- [ ] ~allow all alias (download all episodes)~
- [ ] ~all download a specific episode with the number~

**Comment by kutsan** [comment]
Why wontfix?

**Comment by ryukinix** [comment]
The complexity to do this task is not low and, actually, this feature is beyond to the project, which is just a simple mal command line interface. This is related to #4 which have a brief discussion about the problems behind that.

Even using softwares like youtube-dl, livestreamer and streamlink is not enough. The parsing to title/episode representation for multiple stream/download sources is a big task. The inconsistency of titles from MAL and the anime streams is common. And, as a user @mparadinha commented, can be not very legal too.

After a complete year without any progress with it, I decided dropout this feature. If anyone to make a great proposal implementing that in a sane way, we can think again. But in general this is not priority for now, even being a useful and desired feature. Things like #41 and #46 have more priority and I, as author of the project, I'm trying keep the development more straightfoward to get at least some progress in the next months.

If you have interest to contribute to the project or this specific task, welcome. PR always are welcome. But the main team will not priorize that.

**Comment by ryukinix** [comment]
The tag `wontfix` is not very good for this, besides, this thread is not actually something to fix. Is a feature proposal. Would be better something like `wontimplement` or `dropped`, but I think you get it.

**Comment by kutsan** [comment]
That's fair, I understand. Just saying, instead of downloading the anime, you could just download the relevant torrent file or gather the magnet link from [some websites](https://nyaa.si/). I assume it's not illegal either.

```
transmission-remote --add "$(mal download --magnet 'Serial Experiments Lain 01')"
```

Something like that would be good.

By the way, thanks for this project. I really like it.

**Comment by ryukinix** [comment]
Actually this can be a good idea. Another user proposed something similar on a [reddit thread](https://www.reddit.com/r/commandline/comments/6ykahe/mal_myanimelist_command_line_interface/) another day. But him propose about return a url with video streaming content, which is fair the biggest problem from here (data inconsistency between: MAL data <=> Stream Services URL representation).

About specifically this torrent-based feature, we can try look into it in the future, when the main issues has been fixed. After all, we just need use a torrent search API and get the magnet link with more seeders/leechers proportion. We can use something like [TPB API](https://github.com/karan/TPB).

If you have interest to dig into this, we happyly merge this feature.

**Comment by kutsan** [comment]
Thanks, please use https://nyaa.si too. Also, they provide RSS feeds based on search queries. So, you can even implement that if there is a new episode the user haven't watched yet like this:
https://nyaa.si/?page=rss&term=[HorribleSubs]%20Aho%20Girl%20[1080p]
But this is another story.

I wish I could help but I have no understanding of Python.

**Comment by ghost** [comment]
I recently made a scraper for Nyaa.si for another [project](https://github.com/kryptxy/torrench/pull/21/commits). It works using the project's API but it's very trivial to modify it to work standalone. If anyone here is interested I can modify it to work standalone and you guys could use it in this project.

**Comment by ryukinix** [comment]
Yes, I saw that before. I'm waiting your PR to be merged so then I can test the  `mal` integration with `torrench`. Because some people seems have interest in that, I'll reopen this issue again and remove the  
`wontfix` tag.

**Comment by ryukinix** [comment]
But I don't wanna that can be misunderstood, what I'm saying is valid yet, but I'm reconsidering implement that only for get magnet links or torrent files. Probably I should create a separated issue and implement just a `mal torrent` subcommand, to make this more explicitly. The `download` command for that can be misunderstood. Maybe is better I just create another issue and close that for historical reasons.

Because the meaning of the command described on this issue is a bit more broad than just get torrent files or magnet links.

**Comment by ryukinix** [comment]
@datafanatic and @kutsan I create a new issue covering a prototype about that feature (torrent/magnet-link using nyaa.si) on #64, a feedback based on your concerns would be great. A review of the design choices made will be welcome too.
