### ISSUE TITLE
Search other users anime lists

### ISSUE THREAD

**Issue by mparadinha** [ryukinix/mal#39]
How about a new option like `--user=USERNAME` to search some other users anime list instead of our own when using the program? This would only work on the `list` command of course.
It seems easy to implement

**Comment by alexkubica** [comment]
I like the idea! How about implementing it om `stats` command too?

**Comment by mparadinha** [comment]
Sounds good to me. I can add it to the `stats` command after merging the `stats` branch back into `dev`

**Comment by ryukinix** [comment]
Seems great. I support the idea.
