### ISSUE TITLE
Add subcommand watch

### ISSUE THREAD

**Issue by ryukinix** [ryukinix/mal#4]
## watch

``` bash
mal lain watch next
~opening your default player~
```
## Needs

The #2 need to be fixed before. 
### Specification

After calling watch command, this will fetch the actual episode of the lain, get the next, search on the default streaming server configured, open your default player and update (+1) the watching list.

**Comment by alexkubica** [comment]
I'm sorry if it seems like a stupid question, but what's lain?

**Comment by ryukinix** [comment]
Sorry for this, is an anime: https://myanimelist.net/anime/339/Serial_Experiments_Lain
After see that, maybe is more easily to parse the command that way: `mal watch lain next`. After that command, when I talked with a friend about this command, the functionality is that: open a local player, maybe VLC, using https://pypi.python.org/pypi/livestreamer and get the next episode based the number of MAL account of the user. 

For that we need config a list of open streaming websites about animes, here on Brazil is very common use http://www.superanimes.com/.

This explain better in some way? Sorry for the confusion

**Comment by ryukinix** [comment]
After thinking since the start of the project I'm thinking now to drop out the ideas of implement this and #3. This would be a huge task and make this software a little big.

Crawling streaming video servers and implementing them as interface to multiple sources not seems realistic to make it done on this project. (maybe I'm now being just too pessimistic)

What you think about that? @AlexK-IL @mparadinha.

I'm wondering If I close that as 'no-desired-feature' or just keep open and wait for some magic happens to implement all that.

**Comment by mparadinha** [comment]
It does sound difficult. Also, connecting our project to KissAnime or other websites might not be very legal.

**Comment by ryukinix** [comment]
Yes, we have legal problems too. Well, we have a lot of problems actually with it. Maybe we can keep this simple as is and just remove the old commands already added to mal (yes, we have the subcommands watch and download currently doing nothing)
