### ISSUE TITLE
Find and add new animes to list

### ISSUE THREAD

**Issue by mparadinha** [ryukinix/mal#40]
When I do `mal search` it only shows results that are already on my animelist. Don't know if this was intended, but it would be nice to have that feature as well as being able to add an anime to the list (maybe a `add` command).
I noticed that the `MyAnimeList.search` is not used anywhere in the codebase and it seems to be there for this exact purpose.

- [x] implement new `search` command
- [x] implement `add` command

**Comment by alexkubica** [comment]
It does make sense to `search` all animes on this command. We can make an option for the `list` command that would use the current search implementaion there and change the search command to search for all animes.

**Comment by mparadinha** [comment]
I think we should leave the current behaviour of `search` in the same command but via an option like `--mine`. This way `mal search regex` would search everything and `mal search regex --mine` would only search in the users list. Although `--mine` might not be the best name, not sure.

**Comment by ryukinix** [comment]
Yes, we can use the `mal search regex` as described here. But I propose instead add a new flag for `mal search regex --mine` we can use just `mal filter regex`. Add a bunch of flags will let the CLI complicated very fast. I prefer add a new command `filter` when `search` changed to find all animes on MAL.

**Comment by ryukinix** [comment]
Maybe we can finish that in the next release. For now I'll remove from the release of today.

**Comment by mparadinha** [comment]
The `search` and `filter` commands are basically implemented over at [search-filter](/github/ryukinix/mal/search-filter) but there's a problem with the synopsis (it prints bold tags and the like). Should we just merge it and open an issue to later fix it, or wait till we figure it out?

**Comment by ryukinix** [comment]
Let's wait. After fix the HTML tags we can merge it.

**Comment by mparadinha** [comment]
Fixed the HTML tags in #52. All that's left is to do something to add new animes.
