### ISSUE TITLE
Stats only count rewatches when user is currently rewatching the series

### ISSUE THREAD

**Issue by mparadinha** [ryukinix/mal#42]
This seems to be a problem with the MAL api as discussed on issue #38 and [this commit](https://github.com/ryukinix/mal/commit/576b49e7f7109f5ea3195847927b26de1b7e0f81#commitcomment-20564322).

**Comment by ryukinix** [comment]
Since this is a wontfix, I'll close that for the lack of issue and the respectability of that bug it's external from this project.
