### ISSUE TITLE
Add flag --extend to track more informations on listing

### ISSUE THREAD

**Issue by ryukinix** [ryukinix/mal#5]
More informations can be:
- labels
- start date
- end date.

This will works on list mode.

**Comment by mparadinha** [comment]
How should the output for the extra information be formatted on screen?

**Comment by ryukinix** [comment]
![image](https://cloud.githubusercontent.com/assets/7642878/21968856/3ceede64-db78-11e6-8fae-bdb1ede99955.png)

You can just attach the content below of progress & score line.

**Comment by ryukinix** [comment]
merged into `dev`
