### ISSUE TITLE
Update the README.md about new dependencies, grammar and usage gifs

### ISSUE THREAD

**Issue by ryukinix** [ryukinix/mal#8]
Probably the english in the document is bad (i don't know, but in general my english is pretty bad). 

We need a more clear apresentation too. Removing some gifs?

**Comment by alexkubica** [comment]
How did you generate the gifs?
If you'll approve https://github.com/ryukinix/mal/pull/12 they should be updated too.
Edit:
We can use [asciinema](https://asciinema.org/).

**Comment by ryukinix** [comment]
Yes, we can use asciinema. But i prefer gifs because is embedded and playable directly on github page. I used ttygif written in C, but seems deprecated and a block the son of a bitch whose wrote that shit (horrible implementation, crash my system a lot of times and he shut up my mouth when i created a issue about that). BTW, we need another alternative at which seems be good: https://github.com/sugyan/ttygif

**Comment by alexkubica** [comment]
Is pypandoc still relevant for the dependencies?

**Comment by alexkubica** [comment]
Updated readme on my fork: https://github.com/AlexK-IL/mal/tree/update_readme
A few things are left:
- [x] Verify if pypandoc is needed or not.
- [x] Generate a GIF for demo.
- [x] Review the changes and modify if needed.

**Comment by ryukinix** [comment]
1. Pypandoc is only usefull for upload to pypi, to translate markdown to postscript.
   I think we can omit this on README.md because for users they don't need care about this.

**Comment by ryukinix** [comment]
Thanks for doing that.

**Comment by ryukinix** [comment]
Can you point in README about installation of mal on ArchLinux? This would be great.

**Comment by alexkubica** [comment]
I removed pypandoc: https://github.com/AlexK-IL/mal/commit/2b4cc97f21d949edae61f52d32574ac92e7763e3
And added an installation guide for archlinux: https://github.com/AlexK-IL/mal/commit/f04f612aa31ce86ae3afe489367c9e94aef0ca85
Could you record a gif? My terminal is messed until the next version of decorating.

**Comment by ryukinix** [comment]
# Main Usage

![tty-main](https://cloud.githubusercontent.com/assets/7642878/19803847/59295fd0-9ce1-11e6-9292-7e52266de4af.gif)

# Listing special lists

![tty-list](https://cloud.githubusercontent.com/assets/7642878/19803846/59157a9c-9ce1-11e6-93a7-30665ae859bf.gif)

All another gifs for now is unecessary. Just that two is enough.

**Comment by alexkubica** [comment]
Thanks a lot! I'll add these gifs.

**Comment by ryukinix** [comment]
I update the http://manoel.tk/MAL usage too.

**Comment by alexkubica** [comment]
I think I'm done: https://github.com/AlexK-IL/mal/tree/update_readme
I added the gifs and also updated `decorating` version.
I'll create a PR soon.

**Comment by alexkubica** [comment]
I guess we can close it :)
