### ISSUE TITLE
Create docstrings on code and generate page with readthedocs using sphinx

### ISSUE THREAD

**Issue by ryukinix** [ryukinix/mal#9]
Would be really cool a webpage for documentation like this http://python-packaging-user-guide.readthedocs.io/

Partially done on #25 

- [x] docstrings
- [x] sphinx

**Comment by mparadinha** [comment]
Should we write a man page? I've been looking around on how to do it, and wouldn't mind doing it.

**Comment by ryukinix** [comment]
Would be great.

**Comment by ryukinix** [comment]
We need write better docstrings and setup the sphinx in a better way, but the initial work is done for know after #48
