### ISSUE TITLE
New logo for MAL

### ISSUE THREAD

**Issue by reallinfo** [ryukinix/mal#99]
Hello again @ryukinix , I designed a logo for MAL. How do these look? 

![myanimelist](https://user-images.githubusercontent.com/36298335/39400971-42ecdbea-4b43-11e8-967c-fb26eba3fc2c.jpg)

**Comment by ryukinix** [comment]
Actually I didn't like this icon. The animation icon and the relationship with real Japanese anime seems too abstract for me. Maybe a better anime reference would be great. But, as always, thanks for contributing.
